plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace = 'com.frc2135.frc_scout'
    compileSdk = 37

    defaultConfig {
        applicationId = "com.frc2135.frc_scout"
        minSdk 25
        targetSdk 37
        versionCode = 1
        versionName = "1.0"

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    signingConfigs {
        debug {
            v1SigningEnabled true
            v2SigningEnabled true
            enableV3Signing = false
            enableV4Signing = false
        }
    }

    buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    packaging {
        jniLibs {
            useLegacyPackaging = true
        }
        resources {
            excludes += "/META-INF/{AL2.0,LGPL2.1}"
        }
    }
    bundle {
        language {
            enableSplit = false
        }
        density {
            enableSplit = false
        }
        abi {
            enableSplit = false
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    buildFeatures {
        buildConfig = true
        viewBinding = true
    }
    testOptions {
        unitTests.returnDefaultValues = true
    }
}

dependencies {

    implementation libs.androidx.activity
    implementation libs.androidx.activity.ktx
    implementation libs.androidx.appcompat
    implementation libs.androidx.constraintlayout
    implementation libs.androidx.recyclerview
    implementation libs.androidx.navigation.fragment
    implementation libs.androidx.navigation.ui
    implementation libs.androidx.lifecycle.livedata.ktx
    implementation libs.androidx.lifecycle.viewmodel.ktx
    implementation libs.google.material
    implementation libs.androidx.viewpager2

    implementation libs.volley
    implementation libs.zxing.core

    implementation libs.androidx.work.runtime
    implementation libs.androidx.work.runtime.ktx
    implementation libs.androidx.work.rxjava2
    implementation libs.androidx.work.gcm

    testImplementation libs.junit
    testImplementation libs.mockito.core
    testImplementation libs.org.json
    androidTestImplementation libs.androidx.test.ext.junit
    androidTestImplementation libs.androidx.test.core
    androidTestImplementation libs.androidx.test.monitor
    androidTestImplementation libs.androidx.test.espresso.core
    androidTestImplementation libs.androidx.test.runner
    androidTestImplementation libs.androidx.test.rules
    androidTestImplementation libs.androidx.work.testing
}
